### ISSUE TITLE
Login Fields dont show up

### ISSUE THREAD

**Issue by kayyyy** [firebase/login-demo-ios#13]
I am complete new to the iOS development.
I tried to setup your Demo APP, pasted in my Firebase URL and my Twitter API Key, but i dont get any Login Fields:

![image](https://cloud.githubusercontent.com/assets/8193345/9154534/f58c168a-3e94-11e5-8428-bfb0be9c1884.png)

What could be the issue?

**Comment by hpogosyan** [comment]
@kayyyy the crash is the issue as you can see behind your iOS simulator. I am running into the same issue.

**Comment by mikelehen** [comment]
Can you guys share the details of the crash?

**Comment by hpogosyan** [comment]
@mikelehen 

2015-08-10 09:45:16.379 Login Demo[72758:31323203] Could not locate configuration file: 'GoogleService-Info.plist'.
2015-08-10 09:45:16.380 Login Demo[72758:31323203] Shared configuration dictionary was nil
2015-08-10 09:45:16.381 Login Demo[72758:31323203] *** Assertion failure in -[AppDelegate application:didFinishLaunchingWithOptions:], /Users/johnpogosyan/Downloads/login-demo-ios-master/Login Demo/AppDelegate.m:24
2015-08-10 09:45:16.388 Login Demo[72758:31323203] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error configuring Google services: Error Domain=com.google.greenhouse Code=-200 "Unable to configure GGL." UserInfo=0x7fe998f19160 {NSLocalizedRecoverySuggestion=Check formatting and location of GoogleService-Info.plist., NSLocalizedDescription=Unable to configure GGL., NSLocalizedFailureReason=Unable to parse supplied GoogleService-Info.plist. See log for details.}'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010b120c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010adb9bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010b120aca +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x000000010934598f -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   Login Demo                          0x0000000107aca01a -[AppDelegate application:didFinishLaunchingWithOptions:] + 362
	5   UIKit                               0x0000000109ae8748 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 240
	6   UIKit                               0x0000000109ae9357 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 2540
	7   UIKit                               0x0000000109aec19e -[UIApplication _runWithMainScene:transitionContext:completion:] + 1349
	8   UIKit                               0x0000000109aeb095 -[UIApplication workspaceDidEndTransaction:] + 179
	9   FrontBoardServices                  0x000000010d5c25e5 __31-[FBSSerialQueue performAsync:]_block_invoke_2 + 21
	10  CoreFoundation                      0x000000010b05441c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	11  CoreFoundation                      0x000000010b04a165 __CFRunLoopDoBlocks + 341
	12  CoreFoundation                      0x000000010b049f25 __CFRunLoopRun + 2389
	13  CoreFoundation                      0x000000010b049366 CFRunLoopRunSpecific + 470
	14  UIKit                               0x0000000109aeab02 -[UIApplication _run] + 413
	15  UIKit                               0x0000000109aed8c0 UIApplicationMain + 1282
	16  Login Demo                          0x0000000107aca52f main + 111
	17  libdyld.dylib                       0x000000010b66b145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by hpogosyan** [comment]
You can close this issue, my mind turned into mush and I forgot to follow the rest of the instructions in the Readme after pod install.

**Comment by mikelehen** [comment]
Haha.  Cool.  Thanks for following up!

**Comment by hpogosyan** [comment]
@kayyyy You need to follow the rest of the instructions in the Readme.

**Comment by kayyyy** [comment]
Haha okay thank u. Will to over this als soon aus i am home :)

**Comment by kayyyy** [comment]
Damm auto correction. Will go over this as soon as i am at home.
